In [1]:
import numpy as np

In [2]:
list4 = [1,2,3,4]

In [3]:
[i**2 for i in list4]

[1, 4, 9, 16]

In [4]:
arr = np.array([1,2,3,4])

In [5]:
type(arr)

numpy.ndarray

In [6]:
arr

array([1, 2, 3, 4])

In [7]:
arr **2

array([ 1,  4,  9, 16])

In [8]:
list5 = [i for i in range(1,101)]

In [9]:
arr2 = np.array(list5)

In [10]:
# %timeit [i**2 for i in list5]

In [11]:
# %timeit arr2**2

In [12]:
arr4 = np.arange(1,12,2)

In [13]:
arr4

array([ 1,  3,  5,  7,  9, 11])

In [14]:
sum(arr4)

np.int64(36)

In [15]:
np.sum(arr4)

np.int64(36)

In [16]:
np.min(arr4)

np.int64(1)

In [17]:
np.max(arr4)

np.int64(11)

In [18]:
len(arr4)

6

In [19]:
arr4.size

6

In [20]:
np.array([True,False])

array([ True, False])

In [21]:
np.array([True,False,5])

array([1, 0, 5])

In [22]:
np.array([True,False,5,4.0])

array([1., 0., 5., 4.])

In [23]:
np.array([True,False,5,4.0,"string"])

array(['True', 'False', '5', '4.0', 'string'], dtype='<U32')

In [24]:
np.ones(15,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [25]:
np.zeros(15,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
arr.size

4

In [27]:
arr

array([1, 2, 3, 4])

In [28]:
arr.ndim

1

In [29]:
arr5 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [30]:
arr5.ndim

2

In [31]:
type(arr5)

numpy.ndarray

In [32]:
arr5.size

9

In [33]:
len(arr5)

3

In [34]:
arr

array([1, 2, 3, 4])

In [35]:
arr.shape

(4,)

In [36]:
arr5

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
arr5.shape

(3, 3)

In [38]:
arr6 = np.ones((4,3),dtype=int)

In [39]:
arr6

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [40]:
arr6.ndim

2

In [41]:
arr6.reshape((3,4))

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [42]:
arr7 = np.arange(50,150,10)

In [43]:
arr7

array([ 50,  60,  70,  80,  90, 100, 110, 120, 130, 140])

In [44]:
arr7[[0,2,3]]

array([50, 70, 80])

In [45]:
arr7[4:6]

array([ 90, 100])

In [46]:
list6 = [ 50,  60,  70,  80,  90, 100, 110, 120, 130, 140]

In [47]:
[list6[0],list6[2],list6[3]]

[50, 70, 80]

In [48]:
arr5

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
arr5[1:3,0:2]

array([[4, 5],
       [7, 8]])

In [50]:
arr5[1,0:2]

array([4, 5])

In [51]:
arr5[1,[0,1]]

array([4, 5])

In [52]:
arr5[0,1]

np.int64(2)

In [53]:
arr5

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
arr5[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [55]:
arr7

array([ 50,  60,  70,  80,  90, 100, 110, 120, 130, 140])

In [56]:
sum(arr7)

np.int64(950)

In [57]:
np.sum(arr7)

np.int64(950)

In [58]:
arr5

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
sum(arr5)

array([12, 15, 18])

In [60]:
np.sum(arr5,axis=1)

array([ 6, 15, 24])

In [61]:
np.sum(arr5,axis=0)

array([12, 15, 18])

In [62]:
np.mean(arr5,axis=0)

array([4., 5., 6.])

In [63]:
np.min(arr5,axis=0)

array([1, 2, 3])

In [64]:
np.max(arr5,axis=0)

array([7, 8, 9])

In [65]:
a = np.array([1,2,3,4,5,6,7,8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [66]:
print(a.ndim, a.size)

1 8


In [67]:
array_7 = np.arange(2,16, 2)

# What is the output of    array_7[5 : len(array_7) - 1] ?

array_7

array([ 2,  4,  6,  8, 10, 12, 14])

In [68]:
array_7[5 : len(array_7) - 1]

array([12])

In [69]:
array_7[6:10]

# a) 14
# b) Error
# c) empty array

array([14])

In [70]:
arr7

array([ 50,  60,  70,  80,  90, 100, 110, 120, 130, 140])

In [74]:
mask1 = arr7 > 100 # boolean mask

In [76]:
arr7[mask1]

array([110, 120, 130, 140])

In [77]:
arr7[arr7 > 100]

array([110, 120, 130, 140])

In [78]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [79]:
### task is to fetch elemnts which are greater than 6

In [80]:
a[a>6]

array([7, 8])

In [81]:
### task is to fetch elemnts which are divisible by 2 or 3

In [84]:
a[(a%2==0) | (a%3==0) ]

array([2, 3, 4, 6, 8])

In [85]:
a[(a%2==0) & (a%3==0) ]

array([6])

In [95]:
even_mask = a%2==0

In [96]:
a[even_mask]

array([2, 4, 6, 8])

In [97]:
a[~even_mask]

array([1, 3, 5, 7])

In [99]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [103]:
np.where(a%2==0,"Even","Odd")

array(['Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even'],
      dtype='<U4')

In [104]:
arr11 = np.array([-3, 4, 27, 34, -2, 0, -45, -11, 4, 0])

In [105]:
# - if element is > 0, change it to +1 : cond_1

# - if element <= 0, change it to -1.

In [106]:
np.where(arr11>0,1,-1)

array([-1,  1,  1,  1, -1, -1, -1, -1,  1, -1])

In [107]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [110]:
np.all(a>0)

np.True_

In [112]:
np.any(a>6)

np.True_