In [1]:
import numpy as np

In [2]:
data = np.loadtxt(r"G:\My Drive\Training\Students_Access\July_2025_Batch - MIT\3.0 Python\fit.txt",dtype = str)

In [3]:
date = data[:,0]
step_count = data[:,1]
mood = data[:,2]
calories_burned = data[:,3]
hours_of_sleep = data[:,4]
active = data[:,5]

In [4]:
step_count = step_count.astype(int)
calories_burned = calories_burned.astype(int)
hours_of_sleep = hours_of_sleep.astype(int)

In [5]:
step_count

array([5464, 6041,   25, 5461, 6915, 4545, 4340, 1230,   61, 1258, 3148,
       4687, 4732, 3519, 1580, 2822,  181, 3158, 4383, 3881, 4037,  202,
        292,  330, 2209, 4550, 4435, 4779, 1831, 2255,  539, 5464, 6041,
       4068, 4683, 4033, 6314,  614, 3149, 4005, 4880, 4136,  705,  570,
        269, 4275, 5999, 4421, 6930, 5195,  546,  493,  995, 1163, 6676,
       3608,  774, 1421, 4064, 2725, 5934, 1867, 3721, 2374, 2909, 1648,
        799, 7102, 3941, 7422,  437, 1231, 1696, 4921,  221, 6500, 3575,
       4061,  651,  753,  518, 5537, 4108, 5376, 3066,  177,   36,  299,
       1447, 2599,  702,  133,  153,  500, 2127, 2203])

In [12]:
step_count.mean().round()

2936.0

In [15]:
np.unique(active,return_counts = True)

(array(['Active', 'Inactive'], dtype='<U10'), array([42, 54], dtype=int64))

In [21]:
(40+27)/96

0.6979166666666666

In [19]:
np.unique(mood,return_counts = True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'),
 array([40, 27, 29], dtype=int64))

In [22]:
'''
1. On which day the step count was highest and the calories burned?
hypothesis : more steps count, more calories
'''

'\n1. On which day the step count was highest and the calories burned?\nhypothesis : more steps count, more calories\n'

In [33]:
step_count.mean().round(),calories_burned.mean().round()

(2936.0, 93.0)

In [23]:
np.max(step_count)

7422

In [24]:
np.argmax(step_count)

69

In [27]:
calories_burned[np.argmax(step_count)]

243

In [28]:
np.min(step_count)

25

In [29]:
calories_burned[np.argmin(step_count)]

0

In [32]:
step_count.mean().round(),calories_burned.mean().round()

(2936.0, 93.0)

In [34]:
'''
hypothesis : more steps count, better mood
'''

'\nhypothesis : more steps count, better mood\n'

In [37]:
step_count[mood == "Sad"].mean().round()

2103.0

In [38]:
step_count[mood == "Neutral"].mean().round()

3154.0

In [39]:
step_count[mood == "Happy"].mean().round()

3393.0

In [40]:
# what is my usual mood when step count > 4000 : how many times"

In [44]:
np.unique(mood[step_count > 4000],return_counts = True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'),
 array([22,  9,  7], dtype=int64))

In [45]:
np.unique(mood[step_count < 2000],return_counts = True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'),
 array([13,  8, 18], dtype=int64))