In [2]:
import numpy as np

In [3]:
# !pip install numpy

In [4]:
list5 = [1,2,3,4,5]

In [5]:
[i**2 for i in list5]

[1, 4, 9, 16, 25]

In [6]:
arr = np.array([1,2,3,4,5])

In [7]:
type(arr)

numpy.ndarray

In [8]:
arr

array([1, 2, 3, 4, 5])

In [9]:
arr**2

array([ 1,  4,  9, 16, 25])

In [10]:
list_100 = [i for i in range(1,101)]

In [11]:
arr_100 = np.array(list_100)

In [12]:
# %timeit [i**2 for i in list_100]

In [13]:
# %timeit arr_100**2

In [14]:
arr.ndim

1

In [15]:
arr

array([1, 2, 3, 4, 5])

In [16]:
arr1 = np.arange(1,11)

In [17]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
np.sum(arr1)

55

In [19]:
np.min(arr1)

1

In [20]:
np.max(arr1)

10

In [21]:
arr1.size

10

In [22]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
len(arr1)

10

In [24]:
arr1.shape

(10,)

In [25]:
np.array([True,False])

array([ True, False])

In [26]:
np.array([True,False,5])

array([1, 0, 5])

In [27]:
np.array([True,False,5,6.0])

array([1., 0., 5., 6.])

In [28]:
np.array([True,False,5,6.0,"strr"])

array(['True', 'False', '5', '6.0', 'strr'], dtype='<U32')

In [29]:
np.ones(10,dtype = int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [30]:
np.zeros(10,dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [31]:
arr3 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [32]:
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
type(arr3)

numpy.ndarray

In [34]:
arr3.ndim

2

In [35]:
arr3.size

9

In [36]:
len(arr3)

3

In [37]:
arr3.shape

(3, 3)

In [38]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
arr1[[2,3,5]]

array([3, 4, 6])

In [40]:
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
arr3[0,1]

2

In [42]:
arr3[0,1:]

array([2, 3])

In [43]:
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
arr3[1:,:2]

array([[4, 5],
       [7, 8]])

In [45]:
arr3[[0,1,2],[0,1,0]]

array([1, 5, 7])

In [46]:
arr3[:,0]

array([1, 4, 7])

In [50]:
np.sum(arr3,axis = 1)

array([ 6, 15, 24])

In [48]:
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
np.min(arr3,axis = 0)

array([1, 2, 3])

In [54]:
np.max(arr3,axis = 0)

array([7, 8, 9])

In [56]:
np.mean(arr3,axis = 0)

array([4., 5., 6.])

In [57]:
np.average(arr3,axis = 0)

array([4., 5., 6.])

In [58]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
arr1[arr1 > 5]  # boolean mask

array([ 6,  7,  8,  9, 10])

In [63]:
# find even values

In [64]:
arr1[arr1 % 2 == 0]

array([ 2,  4,  6,  8, 10])

In [69]:
arr1[~(arr1 % 2 == 0)]

array([1, 3, 5, 7, 9])

In [70]:
### task is to fetch elemnts which are divisible by 2 and 3

In [71]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [77]:
arr1[(arr1 % 2 == 0) & (arr1 % 3 == 0)]

array([6])

In [78]:
arr1[(arr1 % 2 == 0) | (arr1 % 3 == 0)]

array([ 2,  3,  4,  6,  8,  9, 10])

In [79]:
np.where(arr1 % 2 == 0,"Even","Odd")

array(['Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd',
       'Even'], dtype='<U4')

In [80]:
arr11 = np.array([-3, 4, 27, 34, -2, 0, -45, -11, 4, 0])

In [82]:
# - if element is > 0, change it to +1 : cond_1

# - if element <= 0, change it to -1.

In [83]:
np.where(arr11>0,1,-1)

array([-1,  1,  1,  1, -1, -1, -1, -1,  1, -1])

In [84]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [89]:
np.all(arr1 > 1)

False

In [93]:
np.any(arr1 > 1)

True