In [49]:
import numpy as np

In [50]:
# !pip install numpy

In [51]:
list5 = [1,2,3,4,5]

In [52]:
[i**2 for i in list5]

[1, 4, 9, 16, 25]

In [53]:
arr = np.array([1,2,3,4,5])

In [54]:
type(arr)

numpy.ndarray

In [55]:
arr

array([1, 2, 3, 4, 5])

In [56]:
arr**2

array([ 1,  4,  9, 16, 25])

In [57]:
list_100 = [i for i in range(1,101)]

In [58]:
arr_100 = np.array(list_100)

In [59]:
# %timeit [i**2 for i in list_100]

In [60]:
# %timeit arr_100**2

In [61]:
arr.ndim

1

In [62]:
arr

array([1, 2, 3, 4, 5])

In [63]:
arr1 = np.arange(1,11)

In [64]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [65]:
np.sum(arr1)

55

In [66]:
np.min(arr1)

1

In [67]:
np.max(arr1)

10

In [68]:
arr1.size

10

In [69]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [70]:
len(arr1)

10

In [71]:
arr1.shape

(10,)

In [77]:
np.array([True,False])

array([ True, False])

In [78]:
np.array([True,False,5])

array([1, 0, 5])

In [80]:
np.array([True,False,5,6.0])

array([1., 0., 5., 6.])

In [81]:
np.array([True,False,5,6.0,"strr"])

array(['True', 'False', '5', '6.0', 'strr'], dtype='<U32')

In [83]:
np.ones(10,dtype = int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [84]:
np.zeros(10,dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [87]:
arr3 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [88]:
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [90]:
type(arr3)

numpy.ndarray

In [91]:
arr3.ndim

2

In [92]:
arr3.size

9

In [93]:
len(arr3)

3

In [94]:
arr3.shape

(3, 3)

In [95]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [106]:
arr1[[2,3,5]]

array([3, 4, 6])

In [108]:
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [109]:
arr3[0,1]

2

In [113]:
arr3[0,1:]

array([2, 3])

In [115]:
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [117]:
arr3[1:,:2]

array([[4, 5],
       [7, 8]])

In [118]:
arr3[[0,1,2],[0,1,0]]

array([1, 5, 7])

In [123]:
arr3[:,0]

array([1, 4, 7])